version: '3.8'

services:
  app:
    ports:
      - "8080:8080"
    build:
      context: ./app
    container_name: arxiv_qa_app
    environment:
      - CHROMA_DB_DIR=/app/chroma_store
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Use the environment variable for OpenAI API key
    volumes:
      - ./app:/app
      - ./chroma_storage:/app/chroma_store
    depends_on:
      - chromadb

    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload" ]
    networks:
      - arxiv_net

  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_storage:/chroma/chroma
    restart: unless-stopped
    networks:
      - arxiv_net

volumes:
  ollama_data:

networks:
  arxiv_net:
    driver: bridge
